### PR TITLE
Update from fb-v2.4 to fb-v2.6 ...

### PR DESCRIPTION
**Pull request by nickurt**

### CODE REVIEW

**Comment by nickurt** [comment]
ping @adamwathan

**Comment by adamwathan** [comment]
Hey @nickurt, can you provide more info about the change? I get that it's likely just a newer version of the API, but what problem does it solve, and are there any breaks to be concerned about? Is the 2.4 API no longer working? Any details around the PR would be helpful. Will happily merge, just don't want to do it blindly, thanks.

**Comment by nickurt** [comment]
The v2.4 api is still working, but I updated it to the latest [version](https://developers.facebook.com/docs/apps/changelog), runned the phpunit scripts and it was giving the expected results. If you want other tests, let me know.

**Comment by adamwathan** [comment]
The PHPUnit tests use fixtures like this: https://github.com/adamwathan/socialnorm-facebook/blob/master/tests/_fixtures/facebook_user.php

...which are copied responses from the Facebook 2.4 API. I would want to confirm that the 2.6 API returns the same data, otherwise the tests are lying :)

**Pull request closed without merging**
